name: Bilibili Content Farm

on: 
  push:
    branches: 
      - master # or the branch where you want these actions to be performed      

jobs:
  generate-text-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Generate text file
      run: |
        # Add commands to generate the new text file here
        echo "Generating the text file..."
        while IFS= read -r line; do
          modified_line="www.bilibili.com##.video-page-card-small:has(div.card-box > div.info > div.upname > a > .name:has-text($line))"
          echo "$modified_line" >> "dist/bilibili_content_farm.txt"
        done < "bilibili_content_farm.txt"        
        echo "Text generation complete."
        
    - name: Commit files
      run: |
        git add .
        git config --local user.email "ken.mercus.lai@gmail.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Bilibili content farm list"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
