name: Bilibili Content Farm

on: 
  push:
    branches: 
      - master # or the branch where you want these actions to be performed      

jobs:
  generate-text-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Generate text file
      run: |
        # Add commands to generate the new text file here
        echo "Generating the text file..."
        rm "dist/bilibili_content_farm.txt"
        echo '! Title: Hide Bilibili Content Farms' >> "dist/bilibili_content_farm.txt"
        echo '! Description: Hide all content farm accounts on Bilibili' >> "dist/bilibili_content_farm.txt"
        current_datetime=$(date +"%Y-%m-%d %H:%M")
        echo "! Last modified: $current_datetime" >> "dist/bilibili_content_farm.txt"
        echo '! Expires: 2 weeks (update frequency)' >> "dist/bilibili_content_farm.txt"
        while IFS= read -r line; do
          modified_line="www.bilibili.com##.video-page-card-small:has(div.card-box > div.info > div.upname > a > .name:has-text($line))"
          echo "$modified_line" >> "dist/bilibili_content_farm.txt"
          modified_line="www.bilibili.com##.is-rcmd.bili-video-card > .__scale-wrap.bili-video-card__wrap:has(div.bili-video-card__info.__scale-disable > div.bili-video-card__info--right > div.bili-video-card__info--bottom > a.bili-video-card__info--owner > span.bili-video-card__info--author:has-text($line))"
          echo "$modified_line" >> "dist/bilibili_content_farm.txt"
        done < "bilibili_content_farm.txt"        
        echo "Text generation complete."
        
    - name: Commit files
      run: |
        git add .
        git config --local user.email "ken.mercus.lai@gmail.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Bilibili content farm list"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
